//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.DataSpecificationPhysicalUnit|DataSpecificationPhysicalUnit}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as newinstancing from '../../newinstancing.generated';
import * as help from './help.generated';

export function DataSpecificationPhysicalUnitFields(
  props: {
    snapInstance: Readonly<aas.types.DataSpecificationPhysicalUnit>,
    instance: aas.types.DataSpecificationPhysicalUnit,
  }
) {
  return (
    <>
      <fields.TextFieldRequired
        label="Unit name"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-unit_name`
        }
        value={props.snapInstance.unitName}
        onChange={
          (value) => {
            props.instance.unitName = value;
          }
        }
      />

      <fields.TextFieldRequired
        label="Unit symbol"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-unit_symbol`
        }
        value={props.snapInstance.unitSymbol}
        onChange={
          (value) => {
            props.instance.unitSymbol = value;
          }
        }
      />

      <fields.ListFieldRequired<aas.types.LangString>
        label="Definition"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-definition`
        }
        newInstanceDefinitions={
          newinstancing.forLangString(
            props.instance
          )
        }
        snapItems={
          props.snapInstance.definition
        }
        items={
          props.instance.definition
        }
        setItems={
          (items) => {
            props.instance.definition = items;
          }
        }
      />

      <fields.TextFieldOptional
        label="SI notation"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-SI_notation`
        }
        value={props.snapInstance.siNotation}
        onChange={
          (value) => {
            props.instance.siNotation = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="SI name"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-SI_name`
        }
        value={props.snapInstance.siName}
        onChange={
          (value) => {
            props.instance.siName = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="DIN notation"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-DIN_notation`
        }
        value={props.snapInstance.dinNotation}
        onChange={
          (value) => {
            props.instance.dinNotation = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="ECE name"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-ECE_name`
        }
        value={props.snapInstance.eceName}
        onChange={
          (value) => {
            props.instance.eceName = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="ECE code"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-ECE_code`
        }
        value={props.snapInstance.eceCode}
        onChange={
          (value) => {
            props.instance.eceCode = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="NIST name"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-NIST_name`
        }
        value={props.snapInstance.nistName}
        onChange={
          (value) => {
            props.instance.nistName = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="Source of definition"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-source_of_definition`
        }
        value={props.snapInstance.sourceOfDefinition}
        onChange={
          (value) => {
            props.instance.sourceOfDefinition = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="Conversion factor"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-conversion_factor`
        }
        value={props.snapInstance.conversionFactor}
        onChange={
          (value) => {
            props.instance.conversionFactor = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="Registration authority id"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-registration_authority_id`
        }
        value={props.snapInstance.registrationAuthorityId}
        onChange={
          (value) => {
            props.instance.registrationAuthorityId = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="Supplier"
        helpUrl={
          `${help.ROOT_URL}/Data_specification_physical_unit.html#property-supplier`
        }
        value={props.snapInstance.supplier}
        onChange={
          (value) => {
            props.instance.supplier = value;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
