//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.EmbeddedDataSpecification|EmbeddedDataSpecification}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";
import * as valtio from "valtio";

import * as enhancing from "../../enhancing.generated";
import * as fields from "../fields";
import * as help from "./help.generated";
import * as model from "../../model";
import * as newinstancing from "../../newinstancing.generated";
import * as verification from "../../verification";
import * as widgets from "../widgets";

export function EmbeddedDataSpecificationFields(
  props: {
    snapInstance: Readonly<aas.types.EmbeddedDataSpecification>,
    instance: aas.types.EmbeddedDataSpecification,
  }
) {
  const [instanceErrors, setInstanceErrors] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const snapErrorSetVersioning = valtio.useSnapshot(
    model.getErrorSet(props.instance).versioning
  );

  React.useEffect(
    () => {
      const [
        anotherInstanceErrors,
        _
      ] = verification.categorizeInstanceErrors(
        model.getErrorSet(props.instance)
      );

      setInstanceErrors(anotherInstanceErrors);
    },
    [
      snapErrorSetVersioning,
      props.instance
    ]
  );
  return (
    <>
    <widgets.LocalErrors errors={instanceErrors} />
      <fields.EmbeddedInstanceRequired<aas.types.Reference>
        label="Data specification"
        helpUrl={
          `${help.ROOT_URL}/Embedded_data_specification.html#property-data_specification`
        }
        parent={props.instance}
        property="dataSpecification"
        snapInstance={
          props.snapInstance.dataSpecification
        }
        instance={
          props.instance.dataSpecification
        }
        newInstanceDefinitions={
          newinstancing.FOR_REFERENCE
        }
        setInstance={
          (instance) => {
            props.instance.dataSpecification = instance;
          }
        }
      />

      <fields.EmbeddedInstanceRequired<aas.types.IDataSpecificationContent>
        label="Data specification content"
        helpUrl={
          `${help.ROOT_URL}/Embedded_data_specification.html#property-data_specification_content`
        }
        parent={props.instance}
        property="dataSpecificationContent"
        snapInstance={
          props.snapInstance.dataSpecificationContent
        }
        instance={
          props.instance.dataSpecificationContent
        }
        newInstanceDefinitions={
          newinstancing.FOR_DATA_SPECIFICATION_CONTENT
        }
        setInstance={
          (instance) => {
            props.instance.dataSpecificationContent = instance;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
