//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.EmbeddedDataSpecification|EmbeddedDataSpecification}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as newinstancing from '../../newinstancing.generated';
import * as help from './help.generated';

export function EmbeddedDataSpecificationFields(
  props: {
    snapInstance: Readonly<aas.types.EmbeddedDataSpecification>,
    instance: aas.types.EmbeddedDataSpecification,
  }
) {
  return (
    <>
      <fields.EmbeddedInstanceRequired<aas.types.Reference>
        label="Data specification"
        helpUrl={
          `${help.ROOT_URL}/Embedded_data_specification.html#property-data_specification`
        }
        snapInstance={
          props.snapInstance.dataSpecification
        }
        instance={
          props.instance.dataSpecification
        }
        newInstanceDefinitions={
          newinstancing.forReference(
            props.instance
          )
        }
        setInstance={
          (instance) => {
            props.instance.dataSpecification = instance;
          }
        }
      />

      <fields.EmbeddedInstanceRequired<aas.types.IDataSpecificationContent>
        label="Data specification content"
        helpUrl={
          `${help.ROOT_URL}/Embedded_data_specification.html#property-data_specification_content`
        }
        snapInstance={
          props.snapInstance.dataSpecificationContent
        }
        instance={
          props.instance.dataSpecificationContent
        }
        newInstanceDefinitions={
          newinstancing.forDataSpecificationContent(
            props.instance
          )
        }
        setInstance={
          (instance) => {
            props.instance.dataSpecificationContent = instance;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
