//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.Key|Key}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";
import * as valtio from "valtio";

import * as enhancing from "../../enhancing.generated";
import * as fields from "../fields";
import * as help from "./help.generated";
import * as model from "../../model";
import * as newinstancing from "../../newinstancing.generated";
import * as verification from "../../verification";
import * as widgets from "../widgets";

export function KeyFields(
  props: {
    snapInstance: Readonly<aas.types.Key>,
    instance: aas.types.Key,
  }
) {
  const [instanceErrors, setInstanceErrors] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const [errorsForType, setErrorsForType] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const [errorsForValue, setErrorsForValue] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const snapErrorSetVersioning = valtio.useSnapshot(
    model.getErrorSet(props.instance).versioning
  );

  React.useEffect(
    () => {
      const [
        anotherInstanceErrors,
        errorsByProperty
      ] = verification.categorizeInstanceErrors(
        model.getErrorSet(props.instance)
      );

      setInstanceErrors(anotherInstanceErrors);

      const anotherErrorsForType =
        errorsByProperty.get("type");
      setErrorsForType(
        anotherErrorsForType === undefined
          ? null
          : anotherErrorsForType
      );

      const anotherErrorsForValue =
        errorsByProperty.get("value");
      setErrorsForValue(
        anotherErrorsForValue === undefined
          ? null
          : anotherErrorsForValue
      );
    },
    [
      snapErrorSetVersioning,
      props.instance
    ]
  );
  return (
    <>
    <widgets.LocalErrors errors={instanceErrors} />
      <fields.EnumerationFieldRequired
        label="Type"
        helpUrl={
          `${help.ROOT_URL}/Key.html#property-type`
        }
        getLiterals={aas.types.overKeyTypes}
        literalToString={aas.stringification.mustKeyTypesToString}
        selected={props.snapInstance.type}
        onChange={
          (value) => {
            props.instance.type = value;
          }
        }
        errors={errorsForType}
      />

      <fields.TextFieldRequired
        label="Value"
        helpUrl={
          `${help.ROOT_URL}/Key.html#property-value`
        }
        value={props.snapInstance.value}
        onChange={
          (value) => {
            props.instance.value = value;
          }
        }
        errors={errorsForValue}
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
