//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.Key|Key}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as help from './help.generated';
import * as newinstancing from '../../newinstancing.generated';

export function KeyFields(
  props: {
    snapInstance: Readonly<aas.types.Key>,
    instance: aas.types.Key,
  }
) {
  return (
    <>
      <fields.EnumerationFieldRequired
        label="Type"
        helpUrl={
          `${help.ROOT_URL}/Key.html#property-type`
        }
        getLiterals={aas.types.overKeyTypes}
        literalToString={aas.stringification.mustKeyTypesToString}
        selected={props.snapInstance.type}
        onChange={
          (value) => {
            props.instance.type = value;
          }
        }
      />

      <fields.TextFieldRequired
        label="Value"
        helpUrl={
          `${help.ROOT_URL}/Key.html#property-value`
        }
        value={props.snapInstance.value}
        onChange={
          (value) => {
            props.instance.value = value;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
