//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.LangString|LangString}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as help from './help.generated';
import * as newinstancing from '../../newinstancing.generated';

export function LangStringFields(
  props: {
    snapInstance: Readonly<aas.types.LangString>,
    instance: aas.types.LangString,
  }
) {
  return (
    <>
      <fields.TextFieldRequired
        label="Language"
        helpUrl={
          `${help.ROOT_URL}/Lang_string.html#property-language`
        }
        value={props.snapInstance.language}
        onChange={
          (value) => {
            props.instance.language = value;
          }
        }
      />

      <fields.TextFieldRequired
        label="Text"
        helpUrl={
          `${help.ROOT_URL}/Lang_string.html#property-text`
        }
        value={props.snapInstance.text}
        onChange={
          (value) => {
            props.instance.text = value;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
