//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.OperationVariable|OperationVariable}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";
import * as valtio from "valtio";

import * as enhancing from "../../enhancing.generated";
import * as fields from "../fields";
import * as help from "./help.generated";
import * as model from "../../model";
import * as newinstancing from "../../newinstancing.generated";
import * as verification from "../../verification";
import * as widgets from "../widgets";

export function OperationVariableFields(
  props: {
    snapInstance: Readonly<aas.types.OperationVariable>,
    instance: aas.types.OperationVariable,
  }
) {
  const [instanceErrors, setInstanceErrors] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const snapErrorSetVersioning = valtio.useSnapshot(
    model.getErrorSet(props.instance).versioning
  );

  React.useEffect(
    () => {
      const [
        anotherInstanceErrors,
        _
      ] = verification.categorizeInstanceErrors(
        model.getErrorSet(props.instance)
      );

      setInstanceErrors(anotherInstanceErrors);
    },
    [
      snapErrorSetVersioning,
      props.instance
    ]
  );
  return (
    <>
    <widgets.LocalErrors errors={instanceErrors} />
      <fields.EmbeddedInstanceRequired<aas.types.ISubmodelElement>
        label="Value"
        helpUrl={
          `${help.ROOT_URL}/Operation_variable.html#property-value`
        }
        parent={props.instance}
        property="value"
        snapInstance={
          props.snapInstance.value
        }
        instance={
          props.instance.value
        }
        newInstanceDefinitions={
          newinstancing.FOR_SUBMODEL_ELEMENT
        }
        setInstance={
          (instance) => {
            props.instance.value = instance;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
