//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.OperationVariable|OperationVariable}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as newinstancing from '../../newinstancing.generated';
import * as help from './help.generated';

export function OperationVariableFields(
  props: {
    snapInstance: Readonly<aas.types.OperationVariable>,
    instance: aas.types.OperationVariable,
  }
) {
  return (
    <>
      <fields.EmbeddedInstanceRequired<aas.types.ISubmodelElement>
        label="Value"
        helpUrl={
          `${help.ROOT_URL}/Operation_variable.html#property-value`
        }
        snapInstance={
          props.snapInstance.value
        }
        instance={
          props.instance.value
        }
        newInstanceDefinitions={
          newinstancing.forSubmodelElement(
            props.instance
          )
        }
        setInstance={
          (instance) => {
            props.instance.value = instance;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
