//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.Qualifier|Qualifier}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";
import * as valtio from "valtio";

import * as enhancing from "../../enhancing.generated";
import * as fields from "../fields";
import * as help from "./help.generated";
import * as model from "../../model";
import * as newinstancing from "../../newinstancing.generated";
import * as verification from "../../verification";
import * as widgets from "../widgets";

export function QualifierFields(
  props: {
    snapInstance: Readonly<aas.types.Qualifier>,
    instance: aas.types.Qualifier,
  }
) {
  const [instanceErrors, setInstanceErrors] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const [errorsForKind, setErrorsForKind] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const [errorsForType, setErrorsForType] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const [errorsForValueType, setErrorsForValueType] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const [errorsForValue, setErrorsForValue] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const snapErrorSetVersioning = valtio.useSnapshot(
    model.getErrorSet(props.instance).versioning
  );

  React.useEffect(
    () => {
      const [
        anotherInstanceErrors,
        errorsByProperty
      ] = verification.categorizeInstanceErrors(
        model.getErrorSet(props.instance)
      );

      setInstanceErrors(anotherInstanceErrors);

      const anotherErrorsForKind =
        errorsByProperty.get("kind");
      setErrorsForKind(
        anotherErrorsForKind === undefined
          ? null
          : anotherErrorsForKind
      );

      const anotherErrorsForType =
        errorsByProperty.get("type");
      setErrorsForType(
        anotherErrorsForType === undefined
          ? null
          : anotherErrorsForType
      );

      const anotherErrorsForValueType =
        errorsByProperty.get("valueType");
      setErrorsForValueType(
        anotherErrorsForValueType === undefined
          ? null
          : anotherErrorsForValueType
      );

      const anotherErrorsForValue =
        errorsByProperty.get("value");
      setErrorsForValue(
        anotherErrorsForValue === undefined
          ? null
          : anotherErrorsForValue
      );
    },
    [
      snapErrorSetVersioning,
      props.instance
    ]
  );
  return (
    <>
    <widgets.LocalErrors errors={instanceErrors} />
      <fields.EmbeddedInstanceOptional<aas.types.Reference>
        label="Semantic id"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-semantic_id`
        }
        parent={props.instance}
        property="semanticId"
        snapInstance={
          props.snapInstance.semanticId
        }
        instance={
          props.instance.semanticId
        }
        newInstanceDefinitions={
          newinstancing.FOR_REFERENCE
        }
        setInstance={
          (instance) => {
            props.instance.semanticId = instance;
          }
        }
      />

      <fields.ListFieldOptional<aas.types.Reference>
        label="Supplemental semantic ids"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-supplemental_semantic_ids`
        }
        parent={props.instance}
        property="supplementalSemanticIds"
        newInstanceDefinitions={
          newinstancing.FOR_REFERENCE
        }
        snapItems={
          props.snapInstance.supplementalSemanticIds
        }
        items={
          props.instance.supplementalSemanticIds
        }
        setItems={
          (items) => {
            props.instance.supplementalSemanticIds = items;
          }
        }
      />

      <fields.EnumerationFieldOptional
        label="Kind"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-kind`
        }
        getLiterals={aas.types.overQualifierKind}
        literalToString={aas.stringification.mustQualifierKindToString}
        selected={props.snapInstance.kind}
        onChange={
          (value) => {
            props.instance.kind = value;
          }
        }
        errors={errorsForKind}
      />

      <fields.TextFieldRequired
        label="Type"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-type`
        }
        value={props.snapInstance.type}
        onChange={
          (value) => {
            props.instance.type = value;
          }
        }
        errors={errorsForType}
      />

      <fields.EnumerationFieldRequired
        label="Value type"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-value_type`
        }
        getLiterals={aas.types.overDataTypeDefXsd}
        literalToString={aas.stringification.mustDataTypeDefXsdToString}
        selected={props.snapInstance.valueType}
        onChange={
          (value) => {
            props.instance.valueType = value;
          }
        }
        errors={errorsForValueType}
      />

      <fields.TextFieldOptional
        label="Value"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-value`
        }
        value={props.snapInstance.value}
        onChange={
          (value) => {
            props.instance.value = value;
          }
        }
        errors={errorsForValue}
      />

      <fields.EmbeddedInstanceOptional<aas.types.Reference>
        label="Value id"
        helpUrl={
          `${help.ROOT_URL}/Qualifier.html#property-value_id`
        }
        parent={props.instance}
        property="valueId"
        snapInstance={
          props.snapInstance.valueId
        }
        instance={
          props.instance.valueId
        }
        newInstanceDefinitions={
          newinstancing.FOR_REFERENCE
        }
        setInstance={
          (instance) => {
            props.instance.valueId = instance;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
