//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.Resource|Resource}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as newinstancing from '../../newinstancing.generated';
import * as help from './help.generated';

export function ResourceFields(
  props: {
    snapInstance: Readonly<aas.types.Resource>,
    instance: aas.types.Resource,
  }
) {
  return (
    <>
      <fields.TextFieldRequired
        label="Path"
        helpUrl={
          `${help.ROOT_URL}/Resource.html#property-path`
        }
        value={props.snapInstance.path}
        onChange={
          (value) => {
            props.instance.path = value;
          }
        }
      />

      <fields.TextFieldOptional
        label="Content type"
        helpUrl={
          `${help.ROOT_URL}/Resource.html#property-content_type`
        }
        value={props.snapInstance.contentType}
        onChange={
          (value) => {
            props.instance.contentType = value;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
