//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.ValueList|ValueList}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";

import * as fields from '../fields';
import * as newinstancing from '../../newinstancing.generated';
import * as help from './help.generated';

export function ValueListFields(
  props: {
    snapInstance: Readonly<aas.types.ValueList>,
    instance: aas.types.ValueList,
  }
) {
  return (
    <>
      <fields.ListFieldRequired<aas.types.ValueReferencePair>
        label="Value reference pairs"
        helpUrl={
          `${help.ROOT_URL}/Value_list.html#property-value_reference_pairs`
        }
        newInstanceDefinitions={
          newinstancing.forValueReferencePair(
            props.instance
          )
        }
        snapItems={
          props.snapInstance.valueReferencePairs
        }
        items={
          props.instance.valueReferencePairs
        }
        setItems={
          (items) => {
            props.instance.valueReferencePairs = items;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
