//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//

/**
 * Define a component with fields corresponding to properties of
 * {@link @aas-core-works/aas-core3.0rc02-typescript#types.ValueList|ValueList}.
 */

import * as aas from "@aas-core-works/aas-core3.0rc02-typescript";
import * as React from "react";
import * as valtio from "valtio";

import * as enhancing from "../../enhancing.generated";
import * as fields from "../fields";
import * as help from "./help.generated";
import * as model from "../../model";
import * as newinstancing from "../../newinstancing.generated";
import * as verification from "../../verification";
import * as widgets from "../widgets";

export function ValueListFields(
  props: {
    snapInstance: Readonly<aas.types.ValueList>,
    instance: aas.types.ValueList,
  }
) {
  const [instanceErrors, setInstanceErrors] = React.useState<
    Array<enhancing.TimestampedError> | null>(null);

  const snapErrorSetVersioning = valtio.useSnapshot(
    model.getErrorSet(props.instance).versioning
  );

  React.useEffect(
    () => {
      const [
        anotherInstanceErrors,
        _
      ] = verification.categorizeInstanceErrors(
        model.getErrorSet(props.instance)
      );

      setInstanceErrors(anotherInstanceErrors);
    },
    [
      snapErrorSetVersioning,
      props.instance
    ]
  );
  return (
    <>
    <widgets.LocalErrors errors={instanceErrors} />
      <fields.ListFieldRequired<aas.types.ValueReferencePair>
        label="Value reference pairs"
        helpUrl={
          `${help.ROOT_URL}/Value_list.html#property-value_reference_pairs`
        }
        parent={props.instance}
        property="valueReferencePairs"
        newInstanceDefinitions={
          newinstancing.FOR_VALUE_REFERENCE_PAIR
        }
        snapItems={
          props.snapInstance.valueReferencePairs
        }
        items={
          props.instance.valueReferencePairs
        }
        setItems={
          (items) => {
            props.instance.valueReferencePairs = items;
          }
        }
      />
    </>
  )
}

//
// WARNING: this code has been automatically generated by codegen.
//
// DO NOT edit or append.
//
