name: CI-codegen

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Execute-continuous-integration-for-codegen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --upgrade coveralls
          pip3 install -e .[dev]
        working-directory: codegen

      - name: Run checks
        run: |
          python3 continuous_integration/precommit.py
        working-directory: codegen
