name: CI

on:
  push:
    branches: [ master, main ]
    tags: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  Build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          # NOTE (mristin, 2023-02-02):
          # For why we set these variables, see this StackOverflow answer:
          # https://stackoverflow.com/a/65615948/1600678
          repo-token: ${{ github.token }}
          repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
