name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
      - mristin/Kick-off
      - jaha-rist-sadu/Kick-off-vite

jobs:
  Generate-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          # NOTE (mristin, 2023-02-02):
          # For why we set these variables, see this StackOverflow answer:
          # https://stackoverflow.com/a/65615948/1600678
          repo-token: ${{ github.token }}
          repository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - run: npm ci
      - run: npm run build

      - name: Deploy to gh-pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
